---
name: Build and push Docker Image to GCR
on:
  push:
    branches: [main]
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: europe-west2 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: abctech    # TODO: update to cluster name
  GKE_ZONE: europe-west2-a # TODO: update to cluster zone
  DEPLOYMENT_NAME: abc # TODO: update to deployment name
  REPOSITORY: article-api # TODO: update to Artifact Registry docker repository
  IMAGE: article-api

jobs:
  build-push-gcr:
    name: Build and Push to GCR
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: article-api
      PROJECT_ID: my-bitnami-hosting
      working-directory: abc-article-api
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      

    - uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID}}
        export_default_credentials: true
    
    - name: 'Create env file'
      run: |-
        echo "${{ secrets.ENV_FILE }}" > .env
      working-directory: abc-article-api

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .
      working-directory: abc-article-api

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Connect to GKE
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Deploy to GKE
      run: |-
        # replacing the image name in the k8s template
        ./kustomize edit set image LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GIT_TAG
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide